"""users table

Revision ID: 4669845aac3c
Revises: 
Create Date: 2020-01-07 14:06:18.578156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4669845aac3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('father', sa.String(length=30), nullable=True),
    sa.Column('mother', sa.String(length=30), nullable=True),
    sa.Column('dateofbirth', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=4), nullable=True),
    sa.Column('bcertno', sa.String(length=17), nullable=True),
    sa.Column('division', sa.String(length=30), nullable=True),
    sa.Column('district', sa.String(length=30), nullable=True),
    sa.Column('thana', sa.String(length=30), nullable=True),
    sa.Column('upazilla', sa.String(length=30), nullable=True),
    sa.Column('village', sa.String(length=30), nullable=True),
    sa.Column('post', sa.String(length=30), nullable=True),
    sa.Column('postcode', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('student')
    # ### end Alembic commands ###
